# Generated by Django 3.0.7 on 2020-06-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_super_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='super_host',
        ),
    ]
