# Generated by Django 3.0.7 on 2020-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200612_2113'),
        ('lists', '0002_auto_20200612_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='Lists', to='rooms.Room'),
        ),
    ]
